language: c
script: make && make travis && ./sslsplit -V
matrix:
  include:
    - os: linux
      compiler: gcc
      env: SSL=ubuntu EVENT=ubuntu
      before_install:
        - sudo apt-get install -qq libssl-dev libevent-dev libnet1-dev libpcap-dev check
    - os: linux
      compiler: clang
      env: SSL=ubuntu EVENT=ubuntu
      before_install:
        - sudo apt-get install -qq libssl-dev libevent-dev libnet1-dev libpcap-dev check
    - os: linux
      compiler: clang
      env: FEATURES=-DWITHOUT_MIRROR SSL=ubuntu EVENT=ubuntu
      before_install:
        - sudo apt-get install -qq libssl-dev libevent-dev check
    - os: linux
      compiler: clang
      env: SSL=openssl-0.9.8zh EVENT=libevent-2.0.22
      cache:
        directories:
          - $HOME/opt
      before_install:
        - sudo apt-get install -qq libnet1-dev libpcap-dev check
      install:
        - ./Mk/bin/install-opt.sh
      before_script:
        - export OPENSSL_BASE="$HOME/opt/$SSL"
        - export LIBEVENT_BASE="$HOME/opt/$EVENT"
        - export LD_LIBRARY_PATH="$HOME/opt/$SSL/lib":"$HOME/opt/$EVENT/lib"
    - os: linux
      compiler: clang
      env: SSL=openssl-1.0.0s EVENT=libevent-2.0.22
      cache:
        directories:
          - $HOME/opt
      before_install:
        - sudo apt-get install -qq libnet1-dev libpcap-dev check
      install:
        - ./Mk/bin/install-opt.sh
      before_script:
        - export OPENSSL_BASE="$HOME/opt/$SSL"
        - export LIBEVENT_BASE="$HOME/opt/$EVENT"
        - export LD_LIBRARY_PATH="$HOME/opt/$SSL/lib":"$HOME/opt/$EVENT/lib"
    - os: linux
      compiler: clang
      env: SSL=openssl-1.0.1u EVENT=libevent-2.0.22
      cache:
        directories:
          - $HOME/opt
      before_install:
        - sudo apt-get install -qq libnet1-dev libpcap-dev check
      install:
        - ./Mk/bin/install-opt.sh
      before_script:
        - export OPENSSL_BASE="$HOME/opt/$SSL"
        - export LIBEVENT_BASE="$HOME/opt/$EVENT"
        - export LD_LIBRARY_PATH="$HOME/opt/$SSL/lib":"$HOME/opt/$EVENT/lib"
    - os: linux
      compiler: clang
      env: SSL=openssl-1.0.2r EVENT=libevent-2.0.22
      cache:
        directories:
          - $HOME/opt
      before_install:
        - sudo apt-get install -qq libnet1-dev libpcap-dev check
      install:
        - ./Mk/bin/install-opt.sh
      before_script:
        - export OPENSSL_BASE="$HOME/opt/$SSL"
        - export LIBEVENT_BASE="$HOME/opt/$EVENT"
        - export LD_LIBRARY_PATH="$HOME/opt/$SSL/lib":"$HOME/opt/$EVENT/lib"
    - os: linux
      compiler: clang
      env: SSL=openssl-1.1.0j EVENT=libevent-2.1.11
      cache:
        directories:
          - $HOME/opt
      before_install:
        - sudo apt-get install -qq libnet1-dev libpcap-dev check
      install:
        - ./Mk/bin/install-opt.sh
      before_script:
        - export OPENSSL_BASE="$HOME/opt/$SSL"
        - export LIBEVENT_BASE="$HOME/opt/$EVENT"
        - export LD_LIBRARY_PATH="$HOME/opt/$SSL/lib":"$HOME/opt/$EVENT/lib"
    - os: linux
      compiler: clang
      env: SSL=openssl-1.1.1c EVENT=libevent-2.1.11
      cache:
        directories:
          - $HOME/opt
      before_install:
        - sudo apt-get install -qq libnet1-dev libpcap-dev check
      install:
        - ./Mk/bin/install-opt.sh
      before_script:
        - export OPENSSL_BASE="$HOME/opt/$SSL"
        - export LIBEVENT_BASE="$HOME/opt/$EVENT"
        - export LD_LIBRARY_PATH="$HOME/opt/$SSL/lib":"$HOME/opt/$EVENT/lib"
    - os: linux
      compiler: clang
      env: SSL=libressl-2.2.7 EVENT=libevent-2.0.22
      cache:
        directories:
          - $HOME/opt
      before_install:
        - sudo apt-get install -qq libnet1-dev libpcap-dev check
      install:
        - ./Mk/bin/install-opt.sh
      before_script:
        - export OPENSSL_BASE="$HOME/opt/$SSL"
        - export LIBEVENT_BASE="$HOME/opt/$EVENT"
        - export LD_LIBRARY_PATH="$HOME/opt/$SSL/lib":"$HOME/opt/$EVENT/lib"
    - os: linux
      compiler: clang
      env: SSL=libressl-2.7.4 EVENT=libevent-2.1.11
      cache:
        directories:
          - $HOME/opt
      before_install:
        - sudo apt-get install -qq libnet1-dev libpcap-dev check
      install:
        - ./Mk/bin/install-opt.sh
      before_script:
        - export OPENSSL_BASE="$HOME/opt/$SSL"
        - export LIBEVENT_BASE="$HOME/opt/$EVENT"
        - export LD_LIBRARY_PATH="$HOME/opt/$SSL/lib":"$HOME/opt/$EVENT/lib"
    - os: osx
      env: SSL=homebrew EVENT=homebrew
      cache:
        directories:
          - /usr/local/Cellar/openssl
          - /usr/local/opt/openssl
          - /usr/local/Cellar/libevent
          - /usr/local/opt/libevent
          - /usr/local/Cellar/libnet
          - /usr/local/opt/libnet
          - /usr/local/Cellar/libpcap
          - /usr/local/opt/libpcap
          - /usr/local/Cellar/check
          - /usr/local/opt/check
      before_install:
        - test -d /usr/local/opt/openssl/lib  || { rmdir /usr/local/opt/openssl; brew install openssl; }
        - test -d /usr/local/opt/libevent/lib || { rmdir /usr/local/opt/libevent; brew install libevent; }
        - test -d /usr/local/opt/libnet/lib   || { rmdir /usr/local/opt/libnet; brew install libnet; }
        - test -d /usr/local/opt/libpcap/lib  || { rmdir /usr/local/opt/libpcap; brew install libpcap; }
        - test -d /usr/local/opt/check/lib    || { rmdir /usr/local/opt/check; brew install check; }
